env:
  browser: true
  es6: true
  jest: true
extends:
  - "plugin:react/recommended"
  - "plugin:@typescript-eslint/recommended"
  - "plugin:jsx-a11y/recommended"
  - standard
  - "plugin:prettier/recommended"
  # - "plugin:react-hooks/recommended"
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
  cy: readonly
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - "@typescript-eslint"
  - react
  - react-hooks
  - jsx-a11y
rules:
  {
    "jsx-a11y/aria-role": [2, { ignoreNonDOM: true }],
    "space-before-function-paren": 0,
    "no-console": 2,
    "react/jsx-uses-react": 2,
    "react-hooks/rules-of-hooks": "error",
    "react-hooks/exhaustive-deps": "warn",
    "react/prop-types": "off",
  }
settings:
  react:
    version: "detect"
